
title: Sparsham Charitable Society
email: info@sparsham.org
description: >
  We are a Society Registered under the Travancore – Cochin Literary, Scientific and Charitable Societies Act, 1955. Act XII of 1955.
  To encourage the students from econmically challenging situations by sponsoring them or arranging facilities like food,study materials, 
  dress and transportation to continue and complete their education, from lower primary to higher secondary.We believe education brings awarness and enlightment to the new generation results into a freedom with responsibilities. 
  Lets extend your hands and join us for developing a new educated and responsible young minds around us.
host : "www.sparsham.org"
baseurl: "" 
url: "https://www.sparsham.org" 
twitter_username: sparshamorg
facebook_username: SparshamCharitableSociety
collections_dir: _collections
include: ["_pages"]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  blog:
    output: true
  campaign:
    output: true
  event:
    output: true 
  articles:
    output: true



